32bit: false
memory: "2048"
npmmirror: "https://registry.npmjs.org/"
owner: "Bot Wrangler <bw@example.com>"
name: "Hubot"
description: "Delightfully aware robutt"
hubot_slack_token: "HUBOT_SLACK_TOKEN ChangeMe"
st2_version: "stable"
use_sources_list: false
